version: '3'
services:
        admin-mongo:
                image: adicom/admin-mongo
                ports:
                        - 8082:8082
                environment:
                        PORT: 8082
                        DB_HOST: mongo
                networks:
                        - public
                        - private

